#数据源
datasource:
    url: jdbc:mysql://localhost:3306/eshop?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    driverClassName: com.mysql.jdbc.Driver



logging:
  level:
    root: INFO
