logging:
  level:
    root: INFO

server:
  port: 9301

spring:
  application:
    name: search
  dubbo:
    server: true
    protocol:
      name: dubbo
      port: 20880
    registry:
      address: zookeeper://192.168.198.131:2181
    scan: com.eshop.search.service