debug: true

logging:
  level:
    root: DEBUG

#数据源
datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234